### ISSUE TITLE
multispec: add a way to use multispec without a version

### ISSUE THREAD

**Issue by TomasTomecek** [devexp-db/distgen#35]
I'm probably doing something stupid:

```
$ dg --distro fedora-26-x86_64.yaml --multispec multispec.yaml --template ./help/help.md --output ./root/help.md
Traceback (most recent call last):
  File "/bin/dg", line 189, in <module>
    main()
  File "/bin/dg", line 185, in main
    render_template(args)
  File "/bin/dg", line 169, in render_template
    explicit_macros,
  File "/usr/lib/python3.6/site-packages/distgen/generator.py", line 231, in render
    spec = merge_yaml(spec, mltspc.select_data(multispec_selectors, config))
  File "/usr/lib/python3.6/site-packages/distgen/multispec.py", line 199, in select_data
    allowed, reason = self.verify_selectors(selectors, distro)
  File "/usr/lib/python3.6/site-packages/distgen/multispec.py", line 164, in verify_selectors
    parsed_selectors = self.parse_selectors(selectors)
  File "/usr/lib/python3.6/site-packages/distgen/multispec.py", line 220, in parse_selectors
    for selector in selectors:
TypeError: 'NoneType' object is not iterable
make: *** [Makefile:22: root/help.md] Error 1
```

```
$ cat multispec.yaml
version: 1

specs:
  distroinfo:
    upstream:
      distros:
        - fedora-26-x86_64
      image_name: modularitycontainers/tools
    fedora:
      distros:
        - fedora-26-x86_64
      image_name: f26/tools
```

In this container image, I don't care about versions. All I really need is to distinguish between upstream and downstream.

**Comment by bkabrda** [comment]
You're doing everything right, this is a bug and I'll fix it.
