### ISSUE TITLE
ASCII error using python 2.7

### ISSUE THREAD

**Issue by kosciCZ** [devexp-db/distgen#53]
Hi, so I have run into this issue with python 2.7 and distgen 0.16 on Fedora 25:
```
/usr/bin/dg --max-passes 25 --distro fedora-26-x86_64.yaml --spec specs/configuration.yml --multispec specs/multispec.yml --multispec-selector variant=upstream --template Dockerfile --output Dockerfile.rendered
/usr/bin/dg --max-passes 25 --distro fedora-26-x86_64.yaml --spec specs/configuration.yml --multispec specs/multispec.yml --multispec-selector variant=upstream --template README.md.template --output README.md
Traceback (most recent call last):
  File "/usr/bin/dg", line 199, in <module>
    main()
  File "/usr/bin/dg", line 195, in main
    render_template(args)
  File "/usr/bin/dg", line 179, in render_template
    args.max_passes,
  File "/usr/lib/python2.7/site-packages/distgen/generator.py", line 269, in render
    env=os.environ,
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1342-1344: ordinal not in range(128)
Makefile:48: návod pro cíl „dg“ selhal
make: *** [dg] Chyba 1
```

This was while trying to build [postfix image](https://github.com/container-images/postfix) ([this PR](https://github.com/container-images/postfix/pull/14) to be specific) using `make run`. 

I have obtained the distgen using `pip`. I was able to workaround this issue by reinstalling with `pip3`.

**Comment by bkabrda** [comment]
Yeah, I can reproduce this using Python 2. There seems to be several different issues with unicode/bytes handling in the code, so I'll try to fix them all. Thanks for reporting this.
